version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    networks:
      defecto:
        aliases:
          - db.sccu
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - defecto
networks:
  defecto:
