version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:4000:4000'
    image: punpat2000/sccu-backend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    image: punpat2000/sccu-web
    links:
      - 'backend:db'
